### ISSUE TITLE
Doesn't compile on nightly, unable to figure out why

### ISSUE THREAD

**Issue by mkroman** [danburkert/procinfo-rs#10] opened 2016-09-13 07:47 UTC
Hi!

I'm working on a project that I want to use `procinfo` in, but when I try to compile it on Rust nightly, is silently fails.

```
mk@maero /tmp/procinfo-rs % cargo build --verbose      
   Compiling nom v1.2.4
   Compiling libc v0.2.16
   Compiling byteorder v0.5.3
     Running `rustc /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/nom-1.2.4/src/lib.rs --crate-name nom --crate-type lib -g --cfg feature=\"stream\" --cfg feature=\"default\" -C metadata=24d7a34b1cbfee73 -C extra-filename=-24d7a34b1cbfee73 --out-dir /tmp/procinfo-rs/target/debug/deps --emit=dep-info,link -L dependency=/tmp/procinfo-rs/target/debug/deps --cap-lints allow`
     Running `rustc /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.16/src/lib.rs --crate-name libc --crate-type lib -g --cfg feature=\"use_std\" --cfg feature=\"default\" -C metadata=1417726cb94dbc83 -C extra-filename=-1417726cb94dbc83 --out-dir /tmp/procinfo-rs/target/debug/deps --emit=dep-info,link -L dependency=/tmp/procinfo-rs/target/debug/deps --cap-lints allow`
     Running `rustc /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-0.5.3/src/lib.rs --crate-name byteorder --crate-type lib -g --cfg feature=\"std\" --cfg feature=\"default\" -C metadata=e4fc6ea0c49cabcf -C extra-filename=-e4fc6ea0c49cabcf --out-dir /tmp/procinfo-rs/target/debug/deps --emit=dep-info,link -L dependency=/tmp/procinfo-rs/target/debug/deps --cap-lints allow`
   Compiling procinfo v0.2.3 (file:///tmp/procinfo-rs)
     Running `rustc src/lib.rs --crate-name procinfo --crate-type lib -g -C metadata=2d7d2b38dbaf2fdc --out-dir /tmp/procinfo-rs/target/debug/deps --emit=dep-info,link -L dependency=/tmp/procinfo-rs/target/debug/deps --extern nom=/tmp/procinfo-rs/target/debug/deps/libnom-24d7a34b1cbfee73.rlib --extern libc=/tmp/procinfo-rs/target/debug/deps/liblibc-1417726cb94dbc83.rlib --extern byteorder=/tmp/procinfo-rs/target/debug/deps/libbyteorder-e4fc6ea0c49cabcf.rlib`
error: Could not compile `procinfo`.
```

Trying to run the `rustc` command with -v (for verbose information) yields no new information either.

```
mk@maero /tmp/procinfo-rs % rustc -v src/lib.rs --crate-name procinfo --crate-type lib -g -C metadata=2d7d2b38dbaf2fdc --out-dir /tmp/procinfo-rs/target/debug/deps --emit=dep-info,link -L dependency=/tmp/procinfo-rs/target/debug/deps --extern nom=/tmp/procinfo-rs/target/debug/deps/libnom-24d7a34b1cbfee73.rlib --extern libc=/tmp/procinfo-rs/target/debug/deps/liblibc-1417726cb94dbc83.rlib --extern byteorder=/tmp/procinfo-rs/target/debug/deps/libbyteorder-e4fc6ea0c49cabcf.rlib 
rustc -v src/lib.rs --crate-name procinfo --crate-type lib -g -C  --out-dir    4,46s user 0,27s system 99% cpu 4,771 total
```

Do you have any ideas what could be causing it? Compiling with Rust stable works fine.

**Comment by danburkert** [comment] 2016-11-05 19:14
Closing as duplicate of #9.  Thanks for the report!

**Closed by danburkert** 2016-11-05 19:14 UTC
